#!/usr/bin/env python3

import lrparsing
from lrparsing import Keyword, List, Prio, Ref, THIS, Token, Tokens


class T(lrparsing.TokenRegistry):
    integer = Token(re="[0-9]+")
    integer["key"] = "I'm a mapping!"
    ident = Token(re="[A-Za-z_][A-Za-z_0-9]*")


class ExprParser(lrparsing.Grammar):
    expr = Ref("expr")
    call = T.ident + '(' + List(expr, ',') + ')'
    atom = T.ident | T.integer | Token('(') + expr + ')' | call
    expr = Prio(
        atom,
        Tokens("+ - ~") >> THIS,
        THIS << Tokens("* / // %") << THIS,
        THIS << Tokens("+ -") << THIS,
        THIS << (Tokens("== !=") | Keyword("is")) << THIS)
    expr["a"] = "I am a mapping too!"
    START = expr
    COMMENTS = (
        Token(re="#(?:[^\r\n]*(?:\r\n?|\n\r?))") |
        Token(re="/[*](?:[^*]|[*][^/])*[*]/"))


parse_tree = ExprParser.parse("1 + /* a */ b + 3 * 4 is c(1, a)")
print(ExprParser.repr_parse_tree(parse_tree))
