#!/usr/bin/env python3

from parsimonious.grammar import Grammar


def main():
    with open('t.gram') as g:
        grammar = Grammar('\n'.join(s for s in g.readlines() if not s.startswith('#')))
        with open('t.nou') as f:
            print(grammar.parse(f.read()))


if '__main__' == __name__:
    main()
