#!/usr/bin/env python3

import re
from parglare import Parser, Grammar

# Model:        Header Object;
# Object:       '{' ID Property+ '}';
# Property:     '-' ID '=' Values SemiColon?;
# Property:     '-' ID '=' SemiColon;
# Values:       Value  | Values SemiColon? Value;
# Value:        STRING | INT | FLOAT | GUID | Object | ID;

# STRING: /("(\\"|[^"])*")|(\'(\\\'|[^\'])*\')/;

# // INT and FLOAT are ambiguous. Prefer INT if both match are of same length.
# INT: /[-+]?[0-9]+\b/ {prefer};
# FLOAT: /[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\b/;

# GUID: /[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]*-[a-f0-9]*/;
# SemiColon: ';';
# ID: /[a-zA-Z_][a-zA-Z_0-9]*/;
# Header: /[^\n]*/;


# grammar = r"""
# E: E '+' E  {left, 1}
#  | E '-' E  {left, 1}
#  | E '*' E  {left, 2}
#  | E '/' E  {left, 2}
#  | E '^' E  {right, 3}
#  | '(' E ')'
#  | number;
# number: /\d+(\.\d+)?/;
# """
# actions = {
#     "E": [lambda _, nodes: nodes[0] + nodes[2],
#           lambda _, nodes: nodes[0] - nodes[2],
#           lambda _, nodes: nodes[0] * nodes[2],
#           lambda _, nodes: nodes[0] / nodes[2],
#           lambda _, nodes: nodes[0] ** nodes[2],
#           lambda _, nodes: nodes[1],
#           lambda _, nodes: nodes[0]],
#     "number": lambda _, value: float(value),
# }
# g = Grammar.from_string(grammar)
# parser = Parser(g, debug=True, actions=actions)
# print("Result = ", parser.parse("34 + 4.6 / 2 * 4^2^2 + 78"))

# header = T.m_header + T.inline
# text = Prio(header, T.line + T.NL) * Many

grammar = '''\
text: block*;
// text: OEB section+[EB] OEB | EB | EMPTY;

@collect
blocks: blocks block | block;
block: section | EB;

// section: header | lines {9};
section: line | EB {9};

@collect_sep
lines: lines NL line | line;
// para: line+ NL line | line;

header: head_mark inline;
head_mark: /^%{1,5}\s/;
inline: /[^\n]+$/;

line: /^[^\n]+$/ {prefer};
OEB: EB | EMPTY;
EB: /[\n]+/;
NL: "\n";
'''

# grammar = '''\
# text: NL* sec_1_NL NL* | EMPTY;
# @collect_sep
# sec_1_NL: sec_1_NL NL+ sec | sec;
# sec: /[^\n]*/;
# NL: "\n";
# '''

# grammar = '''\
# section: header | para;
# header: head_mark line;
# para: line+[NL];
# vempty: NL+;
# head_mark: /^%{1,5}\s/;
# line: /[^\n]+/;
# '''

# Text:       Section | Para;
# Section:    /^%.*$/
# Para:       /.*/

text = '''\
some
%% title

para next word
more lines


% t'''

g = Grammar.from_string(grammar, re_flags=re.MULTILINE)
parser = Parser(g, ws='')
# parser = Parser(g, debug=True)
print(parser.parse(text))
